title: PostMTA Blog
email: help@postmta.com
description: Enterprise Email Infrastructure Guides — KumoMTA, PowerMTA, SMTP, Deliverability
url: https://blog.postmta.com
baseurl: ""
github_url: https://github.com/dchatpar/postmta-blog
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
permalink: /:title/
